CREATE TABLE IF NOT EXISTS holders (
holder_id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
cpf VARCHAR(11) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS accounts (
account_id SERIAL PRIMARY KEY,
number INT NOT NULL,
agency INT NOT NULL,
balance NUMERIC(10, 2) NOT NULL, 
blocked BOOLEAN DEFAULT false,
active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS operations (
operation_id SERIAL PRIMARY KEY,
fk_account INT REFERENCES accounts(account_id),
type VARCHAR(50) NOT NULL,
amount NUMERIC(10, 2) NOT NULL,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
status VARCHAR(50)
);

